project:
  type: website

website:
  title: "Students' Perceptions of AI in Education"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: analysis.qmd
        text: Analysis
      - file: about.qmd
        text: About
      - file: sources.qmd
        text: Sources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



